import { normalizeOsrmRoute, type SavedOsrmRoute } from "@/lib/routing/osrm";
import type { WalkLocation } from "@/types/location";
import type { RouteLeg } from "@/types/navigation";

/**
 * Small helpers every walk module uses to turn its generated JSON files
 * (coordinates.json, routes.json) into app data.
 */

/** The shape of a walk's coordinates.json. */
interface CoordinatesFile {
  locations: { id: string; latitude: number; longitude: number; status?: string }[];
}

/** The shape of a walk's routes.json (written by scripts/generate-walking-routes.mjs). */
interface RoutesFile {
  legs: { fromLocationId: string; toLocationId: string; osrm: unknown }[];
}

/** A stop's position from coordinates.json; `null` coordinates when the stop isn't listed yet. */
export function findPosition(
  file: CoordinatesFile,
  locationId: string,
): Pick<WalkLocation, "coordinates" | "coordinatesStatus"> {
  const entry = file.locations.find((location) => location.id === locationId);
  return {
    coordinates: entry ? { latitude: entry.latitude, longitude: entry.longitude } : null,
    coordinatesStatus: entry?.status === "verified" ? "verified" : "to-verify",
  };
}

/** The walking routes from routes.json, in the app's own format. */
export function loadRouteLegs(file: RoutesFile): RouteLeg[] {
  return file.legs.map((leg) => ({
    fromLocationId: leg.fromLocationId,
    toLocationId: leg.toLocationId,
    // routes.json is generated by our own script in this shape (checked by the data tests).
    route: normalizeOsrmRoute(leg.osrm as SavedOsrmRoute),
  }));
}
