import { normalizeOsrmRoute, type SavedOsrmRoute } from "@/lib/routing/osrm";
import type { WalkLocation } from "@/types/location";
import type { RouteLeg } from "@/types/navigation";

/**
 * Small helpers every walk module uses to turn its generated JSON files
 * (coordinates.json, routes.json) into app data.
 */

/** The shape of a walk's coordinates.json. */
interface CoordinatesFile {
  locations: { id: string; latitude: number; longitude: number; status?: string }[];
}

/** The shape of a walk's routes.json (written by scripts/generate-walking-routes.mjs). */
interface RoutesFile {
  legs: { fromLocationId: string; toLocationId: string; osrm: unknown }[];
}

/** A stop's position from coordinates.json; `null` coordinates when the stop isn't listed yet. */
export function findPosition(
  file: CoordinatesFile,
  locationId: string,
): Pick<WalkLocation, "coordinates" | "coordinatesStatus"> {
  const entry = file.locations.find((location) => location.id === locationId);
  return {
    coordinates: entry ? { latitude: entry.latitude, longitude: entry.longitude } : null,
    coordinatesStatus: entry?.status === "verified" ? "verified" : "to-verify",
  };
}

/** The walking routes from routes.json, in the app's own format. */
export function loadRouteLegs(file: RoutesFile): RouteLeg[] {
  return file.legs.map((leg) => ({
    fromLocationId: leg.fromLocationId,
    toLocationId: leg.toLocationId,
    // routes.json is generated by our own script in this shape (checked by the data tests).
    route: normalizeOsrmRoute(leg.osrm as SavedOsrmRoute),
  }));
}

/**
 * The walk's length as shown on its cards: the route of a walker who skips every
 * optional stop (bypass legs and detours don't count), from one main stop to the
 * next. Rounded to 100 m, because the routes are pre-calculated from draft coordinates.
 */
export function getMainRouteDistance(walkName: string, locations: WalkLocation[], legs: RouteLeg[]): number {
  const mainStops = locations.filter((location) => !location.isBonus).sort((a, b) => a.order - b.order);
  const meters = mainStops.slice(1).reduce((sum, location, index) => {
    const from = mainStops[index].id;
    const leg = legs.find((candidate) => candidate.fromLocationId === from && candidate.toLocationId === location.id);
    if (!leg) throw new Error(`${walkName}: no route ${from} → ${location.id}`);
    return sum + leg.route.distanceMeters;
  }, 0);
  return Math.round(meters / 100) * 100;
}
