import { findPosition, getMainRouteDistance, loadRouteLegs } from "../shared";
import type { CollectionItem, GuideCard, GuideImage, SearchTask } from "@/types/guide";
import type { WalkLocation } from "@/types/location";
import type { RouteLeg } from "@/types/navigation";
import type { Walk } from "@/types/walk";
import classicsImagesFile from "../classics-of-antwerp/images.json";
import { collectionEntries, type CollectionEntry } from "./collection";
import type { Locale } from "@/i18n/config";
import { createTranslator } from "@/i18n/translate";
import { availableLocales, cachePerLocale, pickContent } from "@/i18n/content";
import { poortjesContent } from "./content";
import type { CardText, PoortjesContent, SearchTaskText } from "./content/types";
import coordinatesFile from "./coordinates.json";
import routesFile from "./routes.json";
import { smekensSource, stopDefinitions } from "./stops";

/**
 * "Poortjes van Antwerpen": a narrated guide walk in the footsteps of Paul
 * Smekens' 52 gate drawings (1951).
 *
 *   stops.ts           physical stops in route order (status, sources)
 *   collection.ts      all 52 drawings: number, address, status, caption
 *   content/<lang>/    all text per language (English is the master, Dutch the original)
 *   coordinates.json   stop positions → node scripts/generate-walking-routes.mjs poortjes-van-antwerpen
 *   routes.json        generated by that script (incl. a bypass around optional stops)
 *
 * Vanished gates are collection items only: they never become a location,
 * so the map and GPS never lead the walker to them.
 */

const DRAWING_WIDTH = 1600;
const DRAWING_HEIGHT = 2000;

/** Fills {placeholders} in a content text, e.g. "Plate {plate}". */
function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, name: string) => (name in values ? String(values[name]) : match));
}

/** A drawing from the book, with the credit shown under every image. */
function buildDrawingImage(entry: CollectionEntry, title: string, place: string, content: PoortjesContent): GuideImage {
  const plate = String(entry.plate).padStart(2, "0");
  return {
    id: `smekens-plaat-${entry.plate}`,
    src: `/images/poortjes/gate-${plate}.jpg`,
    width: DRAWING_WIDTH,
    height: DRAWING_HEIGHT,
    alt: fill(content.drawings.alt, { address: place }),
    caption: fill(content.drawings.caption, { plate: entry.plate, title, address: place }),
    approximateYear: "1951",
    photographerOrArtist: "Paul Smekens",
    source: "Oude poortjes in Antwerpen (De Sikkel, 1951)",
    sourceUrl: smekensSource.url ?? "",
    imageUrl: "",
    // TODO: the book is from 1951; get permission (or confirm the rights) before public release.
    license: content.drawings.rightsNote,
    isHistorical: true,
  };
}

function buildCollectionItem(entry: CollectionEntry, content: PoortjesContent): CollectionItem {
  const text = content.collectionItems[entry.plate];
  if (!text) throw new Error(`Poortjes van Antwerpen: missing text for plate ${entry.plate}`);
  const place = text.place ?? entry.address;

  return {
    id: `poort-plaat-${entry.plate}`,
    number: entry.number,
    plateNumber: entry.plate,
    title: text.title,
    address: place,
    status: entry.status,
    image: buildDrawingImage(entry, text.title, place, content),
    chapterId: entry.chapterId,
    stopId: entry.stopId,
    // The book's own words: always the Dutch original.
    sourceCaption: entry.caption,
    sourceCaptionLanguage: "nl",
    note: text.note,
    verification: entry.verification,
  };
}

/** In walk order (1–50), extra items at the end. */
function buildCollectionItems(content: PoortjesContent): CollectionItem[] {
  return collectionEntries
    .map((entry) => buildCollectionItem(entry, content))
    .sort((a, b) => (a.number ?? 999) - (b.number ?? 999) || a.plateNumber - b.plateNumber);
}

type ClassicsImageMetadata = (typeof classicsImagesFile.images)[number];

/** A public-domain photo reused from Classics of Antwerp, with a caption in the walk's language. */
function buildClassicsImage(id: string, content: PoortjesContent): GuideImage {
  const metadata: ClassicsImageMetadata | undefined = classicsImagesFile.images.find((image) => image.id === id);
  const text = content.images[id];
  if (!metadata || !text) throw new Error(`Poortjes van Antwerpen: missing image data for "${id}"`);

  return {
    id,
    src: metadata.localPath,
    width: metadata.width,
    height: metadata.height,
    alt: text.alt,
    caption: text.caption,
    approximateYear: text.approximateYear,
    photographerOrArtist: /^unknown/i.test(metadata.photographerOrArtist.trim()) ? content.drawings.unknownArtist : metadata.photographerOrArtist.trim(),
    source: metadata.source,
    sourceUrl: metadata.sourceUrl,
    imageUrl: metadata.imageUrl,
    license: metadata.license,
    licenseUrl: metadata.licenseUrl ?? undefined,
    isHistorical: !id.endsWith("-today"),
  };
}

function findDrawing(collectionItems: CollectionItem[], plate: number): CollectionItem {
  const item = collectionItems.find((candidate) => candidate.plateNumber === plate);
  if (!item) throw new Error(`Poortjes van Antwerpen: no drawing for plate ${plate}`);
  return item;
}

function buildCard(card: CardText, content: PoortjesContent): GuideCard {
  return {
    id: card.id,
    title: card.title,
    subtitle: card.subtitle,
    image: card.imageId ? buildClassicsImage(card.imageId, content) : undefined,
    sections: card.sections,
    didYouKnow: card.didYouKnow,
  };
}

function buildSearchTask(task: SearchTaskText, stopId: string, collectionItems: CollectionItem[]): SearchTask {
  return {
    title: task.title,
    intro: task.intro,
    hideStoryUntilDone: task.hideStoryUntilDone,
    outro: task.outro,
    items: task.items.map((item) => ({
      id: `${stopId}-plaat-${item.plate}`,
      drawing: findDrawing(collectionItems, item.plate),
      question: item.question,
      hints: item.hints,
      solution: item.solution,
      explanation: item.explanation,
    })),
  };
}

function buildLocations(content: PoortjesContent, collectionItems: CollectionItem[]): WalkLocation[] {
  return stopDefinitions.map((stop, index) => {
    const text = content.stops[stop.id];
    if (!text) throw new Error(`Poortjes van Antwerpen: missing text for "${stop.id}"`);

    const itemsHere = collectionItems.filter((item) => item.stopId === stop.id);
    // Photos for the big stops; gate stops show their drawings via featuredItems instead.
    const images = (stop.classicsImageIds ?? []).map((id) => buildClassicsImage(id, content));

    return {
      id: stop.id,
      order: index + 1,
      name: text.name,
      type: stop.type,
      isBonus: stop.isBonus,
      address: stop.address,
      ...findPosition(coordinatesFile, stop.id),
      description: text.subtitle,
      content: [],
      unlockCondition: index === 0 ? { type: "none" } : { type: "proximity", radiusInMeters: 40 },
      nearbyPlaces: [],
      guide: {
        subtitle: text.subtitle,
        introduction: text.introduction,
        sections: text.sections,
        didYouKnow: text.didYouKnow,
        lookAt: text.lookAt,
        images,
        thenNow: stop.thenNow
          ? { then: buildClassicsImage(stop.thenNow.then, content), now: buildClassicsImage(stop.thenNow.now, content) }
          : undefined,
        transitionToNext: text.transitionToNext,
        closing: text.closing,
        verification: stop.verification,
        sources: stop.sources,
        status: stop.status,
        featuredItems: itemsHere.filter((item) => item.status !== "vanished"),
        vanishedNearby: itemsHere.filter((item) => item.status === "vanished"),
        thenAndNow: text.thenAndNow,
        glossary: (text.glossary ?? []).map((key) => {
          const term = content.glossary[key];
          if (!term) throw new Error(`Poortjes van Antwerpen: unknown glossary term "${key}"`);
          return term;
        }),
        cards: text.cards?.map((card) => buildCard(card, content)),
        searchTask: text.searchTask ? buildSearchTask(text.searchTask, stop.id, collectionItems) : undefined,
        infoBoxes: text.infoBoxes,
      },
    };
  });
}

function buildWalk(content: PoortjesContent, locale: Locale): Walk {
  const routeLegs: RouteLeg[] = loadRouteLegs(routesFile);
  const collectionItems = buildCollectionItems(content);
  const locations = buildLocations(content, collectionItems);

  return {
    id: "walk-poortjes-van-antwerpen",
    slug: "poortjes-van-antwerpen",
    title: content.walk.title,
    tagline: content.walk.tagline,
    shortDescription: content.walk.shortDescription,
    description: content.walk.description,
    city: createTranslator(locale)("common.cities.antwerp"),
    // ± 2 h 45 of walking plus reading at 33 stops and a pause.
    estimatedDuration: { minMinutes: 300, maxMinutes: 390 },
    distanceInMeters: getMainRouteDistance("Poortjes van Antwerpen", locations, routeLegs),
    difficulty: "moderate",
    price: { amountInCents: 1295, currency: "EUR" },
    coverImage: {
      src: "/images/poortjes/gate-07.jpg",
      alt: content.drawings.coverAlt,
    },
    theme: "classic",
    experience: "guide",
    languages: availableLocales(poortjesContent),
    routeReveal: "all",
    team: { minPlayers: 1, maxPlayers: 8 },
    // Researched against the listed sources, but not yet reviewed by a historian or checked on site.
    contentStatus: "placeholder",
    copy: content.walk.copy,
    guideIntro: content.walk.guideIntro,
    highlights: content.walk.highlights,
    howItWorksSteps: content.walk.howItWorksSteps,
    practicalInfo: content.walk.practicalInfo,
    chapters: content.chapters.map((chapter, index) => ({ ...chapter, number: index + 1 })),
    collection: { ...content.walk.collection, items: collectionItems },
    routeLegs,
    locations,
  };
}

/** The walk with its texts in `locale` (English where a translation is missing). */
export const getPoortjesWalk = cachePerLocale((locale) => buildWalk(pickContent(poortjesContent, locale), locale));

/** English, e.g. for tests. */
export const poortjesWalk: Walk = getPoortjesWalk("en");
