import type { Locale } from "@/i18n/config";
import { availableLocales, cachePerLocale, pickContent } from "@/i18n/content";
import { createTranslator } from "@/i18n/translate";
import { loadRouteLegs } from "../shared";
import type { Walk } from "@/types/walk";
import { rococo } from "./01-rococo";
import { denEngel } from "./02-den-engel";
import { patersVaetje } from "./03-paters-vaetje";
import { deMuze } from "./04-de-muze";
import { deKat } from "./05-de-kat";
import { quintenMatsijs } from "./06-quinten-matsijs";
import { deVarkenspoot } from "./07-de-varkenspoot";
import { boerVanTienen } from "./08-boer-van-tienen";
import { hiddenPubsContent } from "./content";
import type { HiddenPubsContent } from "./content/types";
import { finaleClosingStory, finaleQuestions } from "./finale";
import { buildChallenge, buildClue, buildLocation, buildStory } from "./helpers";
import routesFile from "./routes.json";

/**
 * "Hidden Pubs": The Lost Tavern Ledger
 *
 *   01-rococo.ts … 08-boer-van-tienen.ts   one stop each: café, drinks, ledger
 *                                          (FICTION, in Dutch), answers, clue
 *   finale.ts                              the final puzzle's answers
 *   content/<lang>.ts                      all text per language (English is the master)
 *   coordinates.json / routes.json         positions and generated walking routes
 */
const stops = [rococo, denEngel, patersVaetje, deMuze, deKat, quintenMatsijs, deVarkenspoot, boerVanTienen];

function stopText(content: HiddenPubsContent, stopId: string) {
  const text = content.stops[stopId];
  if (!text) throw new Error(`Hidden Pubs: missing text for "${stopId}"`);
  return text;
}

function buildWalk(content: HiddenPubsContent, locale: Locale): Walk {
  return {
    id: "walk-hidden-pubs",
    slug: "hidden-pubs",
    // A brand name: the same in every language.
    title: "Hidden Pubs",
    tagline: content.walk.tagline,
    shortDescription: content.walk.shortDescription,
    description: content.walk.description,
    city: createTranslator(locale)("common.cities.antwerp"),
    // Estimates until the route has been walked and timed.
    estimatedDuration: { minMinutes: 150, maxMinutes: 210 },
    distanceInMeters: null,
    difficulty: "moderate",
    price: { amountInCents: 1495, currency: "EUR" },
    theme: "tavern",
    experience: "game",
    languages: availableLocales(hiddenPubsContent),
    routeReveal: "progressive",
    team: { minPlayers: 1, maxPlayers: 6 },
    // Several challenges and reveals still need on-site verification or sources.
    contentStatus: "placeholder",

    copy: content.walk.copy,
    narrative: content.walk.narrative,
    highlights: content.walk.highlights,
    howItWorksSteps: content.walk.howItWorksSteps,
    practicalInfo: content.walk.practicalInfo,

    finale: {
      title: content.finale.title,
      intro: content.finale.intro,
      questions: finaleQuestions.map((question, index) => buildChallenge(question, content.finale.questions[index])),
      closingStory: buildStory(finaleClosingStory, content.finale.closingStory, locale),
    },
    // Generated by scripts/generate-walking-routes.mjs from coordinates.json.
    routeLegs: loadRouteLegs(routesFile),
    clues: stops.map((stop) => buildClue(stop, stopText(content, stop.id))),
    locations: stops.map((stop) => buildLocation(stop, stopText(content, stop.id), locale)),
  };
}

/** The walk with its texts in `locale` (English where a translation is missing). */
export const getHiddenPubsWalk = cachePerLocale((locale) => buildWalk(pickContent(hiddenPubsContent, locale), locale));

/** English, e.g. for tests. */
export const hiddenPubsWalk: Walk = getHiddenPubsWalk("en");
