import { findPosition, loadRouteLegs } from "../shared";
import type { GuideImage } from "@/types/guide";
import type { WalkLocation } from "@/types/location";
import type { Walk } from "@/types/walk";
import type { Locale } from "@/i18n/config";
import { createTranslator } from "@/i18n/translate";
import { availableLocales, cachePerLocale, pickContent } from "@/i18n/content";
import { classicsContent } from "./content";
import type { ClassicsContent } from "./content/types";
import coordinatesFile from "./coordinates.json";
import imagesFile from "./images.json";
import routesFile from "./routes.json";
import { stopDefinitions } from "./stops";

/**
 * "Classics of Antwerp": a narrated historical walk (experience: "guide").
 *
 *   stops.ts          positions-independent facts, images and sources per stop
 *   content/<lang>.ts all text per language (content/en.ts is the master; see content/index.ts)
 *   coordinates.json  stop positions   → node scripts/generate-walking-routes.mjs classics-of-antwerp
 *   image-sources.json which images    → node scripts/download-commons-images.mjs classics-of-antwerp
 *   images.json, routes.json           generated by those scripts
 */

type ImageMetadata = (typeof imagesFile.images)[number];

/** Commons sometimes repeats "Unknown author"; show a clean name in the visitor's language. */
function cleanArtist(artist: string, unknownLabel: string): string {
  return /^unknown/i.test(artist.trim()) ? unknownLabel : artist.trim();
}

function buildImage(id: string, content: ClassicsContent, unknownLabel: string): GuideImage {
  const metadata: ImageMetadata | undefined = imagesFile.images.find((image) => image.id === id);
  const text = content.images[id];
  if (!metadata || !text) throw new Error(`Classics of Antwerp: missing image data for "${id}"`);

  return {
    id,
    src: metadata.localPath,
    width: metadata.width,
    height: metadata.height,
    alt: text.alt,
    caption: text.caption,
    approximateYear: text.approximateYear,
    photographerOrArtist: cleanArtist(metadata.photographerOrArtist, unknownLabel),
    source: metadata.source,
    sourceUrl: metadata.sourceUrl,
    imageUrl: metadata.imageUrl,
    license: metadata.license,
    licenseUrl: metadata.licenseUrl ?? undefined,
    // Modern comparison photos are stored with ids ending in "-today".
    isHistorical: !id.endsWith("-today"),
  };
}

function buildLocations(content: ClassicsContent, unknownLabel: string): WalkLocation[] {
  return stopDefinitions.map((stop, index) => {
    const text = content.stops[stop.id];
    if (!text) throw new Error(`Classics of Antwerp: missing text for "${stop.id}"`);

    return {
      id: stop.id,
      order: index + 1,
      name: text.name,
      type: stop.type,
      address: stop.address,
      ...findPosition(coordinatesFile, stop.id),
      description: text.subtitle,
      content: [],
      unlockCondition: index === 0 ? { type: "none" } : { type: "proximity", radiusInMeters: 40 },
      nearbyPlaces: [],
      guide: {
        subtitle: text.subtitle,
        introduction: text.introduction,
        sections: text.sections,
        didYouKnow: text.didYouKnow,
        lookAt: text.lookAt,
        images: stop.imageIds.map((id) => buildImage(id, content, unknownLabel)),
        thenNow: stop.thenNow
          ? { then: buildImage(stop.thenNow.then, content, unknownLabel), now: buildImage(stop.thenNow.now, content, unknownLabel) }
          : undefined,
        transitionToNext: text.transitionToNext,
        closing: text.closing,
        verification: stop.verification,
        sources: stop.sources,
      },
    };
  });
}

function buildWalk(content: ClassicsContent, locale: Locale): Walk {
  const t = createTranslator(locale);
  const routeLegs = loadRouteLegs(routesFile);
  const totalMeters = routeLegs.reduce((sum, leg) => sum + leg.route.distanceMeters, 0);

  return {
    id: "walk-classics-of-antwerp",
    slug: "classics-of-antwerp",
    title: content.walk.title,
    tagline: content.walk.tagline,
    shortDescription: content.walk.shortDescription,
    description: content.walk.description,
    city: t("common.cities.antwerp"),
    // About 80 minutes of walking plus reading and looking at 18 stops.
    estimatedDuration: { minMinutes: 165, maxMinutes: 195 },
    // Rounded to 100 m: the routes are pre-calculated from draft coordinates.
    distanceInMeters: Math.round(totalMeters / 100) * 100,
    difficulty: "easy",
    price: { amountInCents: 995, currency: "EUR" },
    coverImage: {
      src: "/images/classics/central-station/historical-1906.jpg",
      alt: content.images["central-station-1906"]?.alt ?? "",
    },
    theme: "archive",
    experience: "guide",
    languages: availableLocales(classicsContent),
    routeReveal: "all",
    team: { minPlayers: 1, maxPlayers: 1 },
    // Researched against the listed sources, but not yet reviewed by a historian.
    contentStatus: "placeholder",
    copy: content.walk.copy,
    guideIntro: content.walk.guideIntro,
    highlights: content.walk.highlights,
    howItWorksSteps: content.walk.howItWorksSteps,
    practicalInfo: content.walk.practicalInfo,
    routeLegs,
    locations: buildLocations(content, t("guide.unknownArtist")),
  };
}

/** The walk with its texts in `locale` (English where a translation is missing). */
export const getClassicsWalk = cachePerLocale((locale) => buildWalk(pickContent(classicsContent, locale), locale));

/** English, e.g. for tests. */
export const classicsOfAntwerpWalk: Walk = getClassicsWalk("en");
